### ISSUE TITLE
Doesn't support PartyAndFriends plugin

### ISSUE THREAD

**Issue by xcrexus** [Phoenix616/Snap#10]
[19:39:51 WARN] [Snap]: Error enabling plugin PartyAndFriends
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:120) ~[?:?]
        at de.themoep.snap.Snap.onProxyInitialization(Snap.java:59) ~[?:?]
        at net.kyori.event.asm.generated.7c4690250f.Snap-onProxyInitialization-ProxyInitializeEvent-3.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[rivacord.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[rivacord.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[rivacord.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[rivacord.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.IllegalStateException: Plugin requires net.md_5.bungee.api.plugin.PluginClassloader
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[rivacord.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at net.md_5.bungee.api.plugin.Plugin.<init>(Plugin.java:34) ~[?:?]
        at de.simonsator.partyandfriends.api.PAFPluginBase.<init>(PAFPluginBase.java:8) ~[?:?]
        at de.simonsator.partyandfriends.main.Main.<init>(Main.java:52) ~[?:?]
        at de.simonsator.partyandfriends.main.PAFPlugin.<init>(PAFPlugin.java:11) ~[?:?]
        ... 17 more

**Comment by Phoenix616** [comment]
Please provide the information requested by the [issue template](https://github.com/Phoenix616/.github/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by kubo6472** [comment]
https://forums.velocitypowered.com/c/plugins/plugin-releases/6/l/top
https://forums.velocitypowered.com/t/party-and-friends-for-velocity-version-1-0-84/420
@xcrexus

**Comment by kubo6472** [comment]
can be closed @Phoenix616 since the plugin has a native velocity version
