### ISSUE TITLE
DeluxeChat Bungee Bridge error

### ISSUE THREAD

**Issue by Artuto** [Phoenix616/Snap#12]
#### Used Version
1.0-SNAPSHOT (build 12)
 
#### Config
Default config
 
#### Environment description
Velocity 1.1.5 
 
#### Full Log
```
[17:44:45 WARN] [Snap]: Error enabling plugin DeluxeChatBungee
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:120) ~[?:?]
        at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
        at net.kyori.event.asm.generated.29f7356a67.Snap-onProxyInitialization-ProxyInitializeEvent-23.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.5]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.5]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velocity.jar:1.1.5]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velocity.jar:1.1.5]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Plugin requires net.md_5.bungee.api.plugin.PluginClassloader
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[velocity.jar:1.1.5]
        at net.md_5.bungee.api.plugin.Plugin.<init>(Plugin.java:34) ~[?:?]
        at me.clip.deluxechat.bungee.DeluxeChatBungee.<init>(DeluxeChatBungee.java:26) ~[?:?]
        ... 17 more
```

#### What other programs/plugins are you running?
None

#### What is happening?
1. Drop the DeluxeChat jar (can provide) into the snap plugins folder.
2. Start the server

#### What did you expect to happen?
The plugin to load.

#### Additional context
That change was introduced here https://github.com/SpigotMC/BungeeCord/commit/f41b1fc82131842409fed2df1c702cda36b06bd2

**Comment by Phoenix616** [comment]
Seeing as this is not a freely available resource the author/a copyright holder will have to provide their code/the resource so that can be tested as that is clearly an issue with how they created it.

It isn't a bug with loading plugins in Snap in general as the mentioned commit was already included in Snap and it was able to load other plugins just fine.

**Comment by Artuto** [comment]
I can provide the plugin jar over discord if that's okay

**Comment by Phoenix616** [comment]
@Artuto I highly doubt you have the rights to distribute it and I want nothing to do with copyright violation.
