### ISSUE TITLE
BungeeJail cannot find some class

### ISSUE THREAD

**Issue by U-ENERGY** [Phoenix616/Snap#13]
#### Used Version

 1.0-SNAPSHOT (build 16)
 
#### Config
default
 
#### Environment description

 Windows Server 2019. Velocity 1.1.8
 
#### Full Log

```

> [04:50:28 WARN] [Snap]: Exception encountered when loading plugin: BungeeJail
java.lang.NoClassDefFoundError: net/md_5/bungee/BungeeCord
	at de.Max98LP.BungeeJail.JailManager.loadConfig(JailManager.java:42) ~[?:?]
	at de.Max98LP.BungeeJail.JailManager.<init>(JailManager.java:27) ~[?:?]
	at de.Max98LP.BungeeJail.Main.onEnable(Main.java:55) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[?:?]
	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121) ~[?:?]
	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
	at net.kyori.event.asm.generated.fded1c4226.Snap-onProxyInitialization-ProxyInitializeEvent-26.invoke(Unknown Source) ~[?:?]
	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.9-SNAPSHOT (git-793ad443-b443)]
	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.9-SNAPSHOT (git-793ad443-b443)]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velocity.jar:1.1.9-SNAPSHOT (git-793ad443-b443)]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velocity.jar:1.1.9-SNAPSHOT (git-793ad443-b443)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.BungeeCord
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:85) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:67) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 15 more

```

#### What other programs/plugins are you running?

LuckPerms, Snap

#### What is happening?

What is happening?

#### What did you expect to happen?

Yes.

**Comment by U-ENERGY** [comment]
Forgot the link.  https://www.spigotmc.org/resources/bungeejail.8280/

**Comment by Phoenix616** [comment]
The class `net/md_5/bungee/BungeeCord` is not part of BungeeCord's API but the server implementation so that cannot be supported. The plugin dev should use the proper API class (ProxyServer) instead.
