### ISSUE TITLE
BungeeTabListPlus does not function properly, but does load.

### ISSUE THREAD

**Issue by RealTriassic** [Phoenix616/Snap#14]
#### Used Version

 BungeeTabListPlus v3.4.3
 
#### Config

 ```yaml
# This is the configuration file of BungeeTabListPlus
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki for additional information

# if enabled the plugin checks for new versions automatically.
# Use /BTLP to see whether a new version is available
# this does NOT automatically install an update
checkForUpdates: true

# Custom placeholders
customPlaceholders: {}

# Disables the custom tab list for players in spectators mode.
# As a result those players will see the vanilla tab list of the server.
# If you do not use this option players in spectator mode will see the 
# fake players created by BungeeTabListPlus in the teleport menu.
disableCustomTabListForSpectators: true

# Servers which you wish to show their own tabList (The one provided by bukkit)
# Players on these servers don't see the custom tab list provided by BungeeTabListPlus
excludeServers: []

# Removes the `~BTLP Slot ##` entries from tab completion if the.
# size of the tab list is 80 slots.
experimentalTabCompleteFixForTabSize80: false

# Replaces the `~BTLP Slot ##` entries in tab completion with smileys
experimentalTabCompleteSmileys: false

# those fakeplayers will randomly appear on the tablist. If you don't put any names there then no fakeplayers will appear
fakePlayers: []

# players which are permanently hidden from the tab list
# you can either put your username or your uuid (with dashes) here
# don't use this. you have absolutely no reason to hide from anyone. on your own server.
hiddenPlayers: []

# Players on these servers are hidden from the tab list.
# Doesn't necessarily hide the server from the tab list.
hiddenServers: []

# this notifies admins (everyone with the permission `bungeetablistplus.admin`) if an update is available
notifyAdminsIfUpdateAvailable: true

# Interval (in seconds) at which all servers of your network get pinged to check whether they are online
# If you intend to use the {onlineState:SERVER} variable set this to 2 or any value you like
# setting this to -1 disables this feature
pingDelay: -1
time_zone: Etc/UTC
 ```
 
#### Full Log

```
[07:16:43 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: net/md_5/bungee/UserConnection
        at codecrafter47.bungeetablistplus.util.ReflectionUtil.getChannelWrapper(ReflectionUtil.java:37) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.createTabView(TabViewManager.java:126) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.onPlayerJoin(TabViewManager.java:71) ~[?:?]
        at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
        at de.themoep.snap.forwarding.listener.PostLoginListener.on(PostLoginListener.java:33) ~[?:?]
        at net.kyori.event.asm.generated.86f78c8a83.PostLoginListener-on-PostLoginEvent-22.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[server.jar:1.1.8]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[server.jar:1.1.8]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[server.jar:1.1.8]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[server.jar:1.1.8]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.UserConnection
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:85) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:67) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 21 more
```

#### What other programs/plugins are you running?

LuckPerms 5.3.47, Snap 1.0-pre2.

#### What is happening?

Tablist falls back to the vanilla tablist and BungeeTabListPlus throws an error.

#### What did you expect to happen?

The Tablist should display properly when being viewed.

**Comment by Phoenix616** [comment]
The plugin uses internal classes instead of just the API so this is impossible to support in Snap.
