### ISSUE TITLE
Two functions are missing

### ISSUE THREAD

**Issue by crafter23456** [Phoenix616/Snap#18]
#### Used Version
snap 1.0-SNAPSHOT (build 23) by Phoenix616
 
#### Full Log
```
[22:27:54] [main/INFO]: Booting up Velocity 3.0.0...
[22:27:54] [main/INFO]: Loading localizations...
[22:27:55] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[22:27:55] [main/INFO]: Loading plugins...
[22:27:55] [main/ERROR]: Unable to load plugin plugins/AtParty-1.0.1-SNAPSHOT.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file AtParty-1.0.1-SNAPSHOT.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoader.java:61) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:93) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[Velocity.jar:3.0.0]
[22:27:55] [main/ERROR]: Unable to load plugin plugins/Log-Tool-For-Party-And-Friends-1.0.4-SNAPSHOT.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file Log-Tool-For-Party-And-Friends-1.0.4-SNAPSHOT.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoader.java:61) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:93) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[Velocity.jar:3.0.0]
[22:27:55] [main/ERROR]: Unable to load plugin plugins/MaxFriends-1.0.3-SNAPSHOT.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file MaxFriends-1.0.3-SNAPSHOT.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoader.java:61) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:93) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[Velocity.jar:3.0.0]
[22:27:55] [main/INFO]: Loaded plugin luckperms 5.3.51 by Luck
[22:27:55] [main/INFO]: Loaded plugin advancedban 2.4.0 by 
[22:27:55] [main/INFO]: Loaded plugin broadcast 1.0.0 by OskarZyg, OskarsMC
[22:27:55] [main/INFO]: Loaded MySQL for Velocity!
[22:27:55] [main/INFO]: Loaded plugin mysqlandconfigurateforvelocity 8.0.20 by Simonsator
[22:27:55] [main/INFO]: Loaded plugin partyandfriends 1.0.216-E by Simonsator
[22:27:55] [main/INFO]: Loaded plugin clans-loader 0.9.9.28 by Simonsator
[22:27:55] [main/INFO]: Took 166ms to boot Floodgate
[22:27:55] [main/INFO]: Loaded plugin floodgate 2.0-SNAPSHOT by GeyserMC
[22:27:55] [main/INFO]: Loaded plugin geyser 1.4.1-SNAPSHOT (git-master-ba4e0cf) by GeyserMC
[22:27:55] [main/INFO]: Loaded plugin send 2.0.0 by OskarsMC, OskarZyg
[22:27:55] [main/INFO]: Loaded plugin snap 1.0-SNAPSHOT (build 23) by Phoenix616
[22:27:55] [main/INFO]: Loaded 10 plugins
[22:27:56] [Velocity Async Event Executor - #0/INFO]:         __    
[22:27:56] [Velocity Async Event Executor - #0/INFO]:   |    |__)   LuckPerms v5.3.51
[22:27:56] [Velocity Async Event Executor - #0/INFO]:   |___ |      Running on Velocity - Velocity
[22:27:56] [Velocity Async Event Executor - #0/INFO]: 
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loading configuration...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loading storage provider... [MARIADB]
[22:27:56] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Starting...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Start completed.
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loading messaging service... [SQL]
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loading internal permission managers...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Performing initial data load...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Successfully enabled. (took 695ms)
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded snap.conf
[22:27:56] [Velocity Async Event Executor - #0/WARN]: Could not initialize LibraryLoader (missing dependencies?)
[22:27:56] [Velocity Async Event Executor - #0/WARN]: PartyAndFriends (required by FRL) is unavailable
[22:27:56] [Velocity Async Event Executor - #0/WARN]: Failed to enable FRL
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin SCAutoBroadcaster version 1.2.1 by sidecrew
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin BungeePlayTime version 0.0.2 by NoOneYouKnow
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin DBVerifier version 1.6.5 by StaticRed
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Creating default config...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loading config...
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin JoinMe version 2.0 by Fabb111
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin BuycraftX version 12.0.6 by Buycraft
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin protocolize-plugin version 1.7.1-SNAPSHOT:629 by Exceptionflug
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin PL-Hide-Pro version 1.5.2 by Nononitas
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin ReportSystem version 1.4 by nomis_s
[22:27:56] [Velocity Async Event Executor - #0/WARN]: Geyser-BungeeCord (required by GeyserSkinManager-BungeeCord) is unavailable
[22:27:56] [Velocity Async Event Executor - #0/WARN]: Failed to enable GeyserSkinManager-BungeeCord
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Loaded plugin GeyserPreventServerSwitch version 1.1-SNAPSHOT by Camotoy
[22:27:56] [Velocity Async Event Executor - #0/WARN]: Exception encountered when loading plugin: SCAutoBroadcaster
java.lang.NoClassDefFoundError: net/md_5/bungee/BungeeCord
	at spigot.sidecrew.bungeebroadcaster.managers.ConfigManager.loadConfiguration(ConfigManager.java:38) ~[?:?]
	at spigot.sidecrew.bungeebroadcaster.managers.ConfigManager.<init>(ConfigManager.java:22) ~[?:?]
	at spigot.sidecrew.bungeebroadcaster.Main.onEnable(Main.java:28) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[?:?]
	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121) ~[?:?]
	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
	at de.themoep.snap.Lmbda$13.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[Velocity.jar:3.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.BungeeCord
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 13 more
[22:27:56] [Velocity Async Event Executor - #0/INFO]: Enabled plugin BungeePlayTime version 0.0.2 by NoOneYouKnow
[22:27:57] [Velocity Async Event Executor - #0/INFO]: Login Successful!
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b----------------------------------------------------
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b ___   ___ __   __           _   __  _           
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b|   \ | _ )\ \ / / ___  _ _ (_) / _|(_) ___  _ _ 
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b| |) || _ \ \   / / -_)| '_|| ||  _|| |/ -_)| '_|
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b|___/ |___/  \_/  \___||_|  |_||_|  |_|\___||_|  
[22:27:57] [Velocity Async Event Executor - #0/INFO]: ?b------------DBVerifier 1.6.5 by StaticRed------------
[22:27:57] [Velocity Async Event Executor - #0/INFO]: Enabled plugin DBVerifier version 1.6.5 by StaticRed
[22:27:57] [Velocity Async Event Executor - #0/INFO]: Registering command joinme (1 aliases)...
[22:27:57] [Velocity Async Event Executor - #0/INFO]: Enabled plugin JoinMe version 2.0 by Fabb111
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: java.lang.ClassNotFoundException: net.md_5.bungee.netty.PipelineUtils
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.Class.forName0(Native Method)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.Class.forName(Class.java:375)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at net.buycraft.plugin.bungeecord.httplistener.BungeeNettyChannelInjector.inject(BungeeNettyChannelInjector.java:16)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at net.buycraft.plugin.bungeecord.BuycraftPlugin.onEnable(BuycraftPlugin.java:86)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at de.themoep.snap.Lmbda$13.execute(Unknown Source)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:27:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[22:27:57] [Velocity Async Event Executor - #0/INFO]: Validating your server key...
[22:27:57] [JDA MainWS-ReadThread/INFO]: Connected to WebSocket
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Enabled plugin BuycraftX version 12.0.6 by Buycraft
[22:27:58] [Velocity Async Event Executor - #0/INFO]: ======= PROTOCOLIZE =======
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Version 1.7.1-SNAPSHOT:629 by Exceptionflug
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.ChangeGameState
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.NamedSoundEffect
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPosition
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerLook
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPositionLook
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.SetSlot
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.WindowItems
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.UseItem
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.BlockPlacement
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.OpenWindow
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.WindowProperty
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ClickWindow
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Enabled plugin protocolize-plugin version 1.7.1-SNAPSHOT:629 by Exceptionflug
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Enabled plugin PL-Hide-Pro version 1.5.2 by Nononitas
[22:27:58] [Velocity Async Event Executor - #0/WARN]: Exception encountered when loading plugin: ReportSystem
java.lang.NoClassDefFoundError: net/md_5/bungee/BungeeCord
	at de.simon.report.main.Main.onEnable(Main.java:45) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[?:?]
	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121) ~[?:?]
	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
	at de.themoep.snap.Lmbda$13.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[Velocity.jar:3.0.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[Velocity.jar:3.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.BungeeCord
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 11 more
[22:27:58] [Velocity Async Event Executor - #0/ERROR]: Geyser-BungeeCord not found! Disabling...
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Enabled plugin GeyserPreventServerSwitch version 1.1-SNAPSHOT by Camotoy
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Loaded 9 plugins!
[22:27:58] [JDA MainWS-ReadThread/INFO]: Finished Loading!
[22:27:58] [Velocity Async Event Executor - #0/INFO]: Party and Friends: Multi Core Enhancement is activated.
[22:27:58] [Velocity Async Event Executor - #0/WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:27:58] [Velocity Async Event Executor - #0/WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:27:58] [Velocity Async Event Executor - #0/INFO]: [AdvancedBan] Offline permission support through LuckPerms active
[22:27:58] [Velocity Async Event Executor - #0/INFO]: HikariPool-1 - Starting...
[22:27:58] [Velocity Async Event Executor - #0/INFO]: HikariPool-1 - Start completed.
[22:27:58] [Velocity Async Event Executor - #0/INFO]: 
 
&8[]=====[&7Enabling AdvancedBan&8]=====[]
&8| &cInformation:
&8|   &cName: &7AdvancedBan
&8|   &cDeveloper: &7Leoko
&8|   &cVersion: &72.4.0
&8|   &cStorage: &7MySQL (external)
&8| &cSupport:
&8|   &cGithub: &7https://github.com/DevLeoko/AdvancedBan/issues
&8|   &cDiscord: &7https://discord.gg/ycDG6rS
&8| &cTwitter: &7@LeokoGar
&8| &cUpdate:
&8|   &7There is a new version available! [2.3.0]
&8[]================================[]&r
 
[22:27:59] [Velocity Async Event Executor - #0/INFO]: Auto-loaded Floodgate key
[22:27:59] [Velocity Async Event Executor - #0/INFO]: ******************************************
[22:27:59] [Velocity Async Event Executor - #0/INFO]: 
[22:27:59] [Velocity Async Event Executor - #0/INFO]: Loading Geyser version 1.4.1-SNAPSHOT (git-master-ba4e0cf)
[22:27:59] [Velocity Async Event Executor - #0/INFO]: 
[22:27:59] [Velocity Async Event Executor - #0/INFO]: ******************************************
[22:27:59] [Thread-16/WARN]: 
**********************************
* The prefix you entered in your Floodgate config (PE_) could lead to username conflicts!
* Should a Java player join with the username PE_Notch, and a Bedrock player join as Notch (who will be given the name PE_Notch), unwanted results will happen!
* We strongly recommend using . as the prefix, but other alternatives that will not conflict include: +, - and *
**********************************
[22:28:04] [Velocity Async Event Executor - #0/INFO]: Loaded Floodgate key!
[22:28:04] [Velocity Async Event Executor - #0/INFO]: Started Geyser on 0.0.0.0:19132
[22:28:04] [Velocity Async Event Executor - #0/INFO]: Done (5.399s)! Run /geyser help for help!

```

#### What is happening?
The ReportSystem & SCAutoBroadcaster need the `java.lang.NoClassDefFoundError: net/md_5/bungee/BungeeCord` class
Buycraft needs the `java.lang.ClassNotFoundException: net.md_5.bungee.netty.PipelineUtils` class

#### Additional context
Don't judge me for using geyser & the three PAF plugins are only for testing there from other project because these bungee plugins need a velocity plugin, but because they are not at the same path yeah, I know a workaround for it, so no problem :P Keep up your work!

**Comment by Phoenix616** [comment]
These classes are internal to Bungeecord and not API so it's impossible to make compatible. They have to use the API properly.
