### ISSUE TITLE
JPremium not working.

### ISSUE THREAD

**Issue by ultraic-space** [Phoenix616/Snap#22]
#### Used Version
Loaded plugin snap 1.0-pre2 (build 16) by Phoenix616
 
 
#### Config
 ```yaml
{
    # configurate-hocon
    # The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
    "stats-id" : "1563e663-32c9-44f6-b042-b4d6fdcaffd0",
    # configurate-hocon
    # Whether to throw exceptions when accessing methods that aren't supported
    # Setting this to false makes them return sensible values but they might not be correct
    "throw-unsupported-exception" : false
}

 ```
 
#### Environment description
Using purpur on sub-servers (issue also happens with paper) with velocity enabled on pterodactyl. Using premium server host.
 
#### Full Log
```
[16:12:50] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[16:12:50] [main/INFO]: Done (5.35s)!
[16:16:38] [Netty NIO Worker #1/INFO]: [connected player] Ultraic (/127.0.0.1:61263) has connected
[16:16:38] [Velocity Async Event Executor - #5/WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=null, connection=de.themoep.snap.forwarding.SnapPlayer$1@672d70ec) to listener com.jakub.premium.c.c@3b75a4bb
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/InitialHandler
	at com.jakub.premium.c.c.a(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
	at de.themoep.snap.forwarding.listener.LoginListener.on(LoginListener.java:46) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$5.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.InitialHandler
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:85) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:67) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 16 more
[16:16:38] [Velocity Async Event Executor - #6/WARN]: Error dispatching event PostLoginEvent(player=de.themoep.snap.forwarding.SnapPlayer@71051bc3) to listener com.jakub.premium.c.d@13a669ca
java.lang.NullPointerException: Cannot invoke "com.jakub.premium.f.a.getSessionExpires()" because "<local4>" is null
	at com.jakub.premium.c.d.a(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
	at de.themoep.snap.forwarding.listener.PostLoginListener.on(PostLoginListener.java:33) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$9.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[16:16:38] [Velocity Async Event Executor - #7/WARN]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@71051bc3, target=de.themoep.snap.forwarding.SnapServerInfo@64f6f5a5, reason=UNKNOWN, request=null, cancelled=false) to listener com.jakub.premium.c.f@5e83b9a1
java.lang.NullPointerException: Cannot invoke "com.jakub.premium.f.a.isLogged()" because "<parameter1>" is null
	at com.jakub.premium.d.d.b(Unknown Source) ~[?:?]
	at com.jakub.premium.c.f.a(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
	at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$15.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[16:16:38] [Netty NIO Worker #1/INFO]: [server connection] Ultraic -> lobby has connected
[16:16:38] [Netty NIO Worker #1/INFO]: [server connection] Ultraic -> lobby has disconnected
[16:16:38] [Netty NIO Worker #1/ERROR]: [connected player] Ultraic (/127.0.0.1:61263): disconnected while connecting to lobby: [»] Please join to the server via ultraic.space!
[16:16:38] [Velocity Async Event Executor - #0/WARN]: Error dispatching event ServerKickEvent(cancelled=true, player=de.themoep.snap.forwarding.SnapPlayer@71051bc3, kickedFrom=de.themoep.snap.forwarding.SnapServerInfo@64f6f5a5, kickReasonComponent=[BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)], cancelServer=null, state=CONNECTED, cause=UNKNOWN) to listener com.jakub.premium.c.h@37e8ab27
java.lang.NullPointerException: Cannot invoke "com.jakub.premium.f.a.isLogged()" because "<local5>" is null
	at com.jakub.premium.c.h.a(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
	at de.themoep.snap.forwarding.listener.ServerKickListener.on(ServerKickListener.java:49) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$17.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.0]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[16:16:38] [Netty NIO Worker #1/INFO]: [connected player] Ultraic (/127.0.0.1:61263) has disconnected: [»] Please join to the server via ultraic.space!
```

#### What other programs/plugins are you running?
Just snap & Premium + the latest stable version of Velocity.

#### What is happening?
JPremium doesn't seem to be sending the proper validation code to the lobby server, resulting in the player getting kicked and the "Please join to the server via <server.ip>" message.

#### What did you expect to happen?
Be able to connect to lobby server without any issues. Have not tested further (e.g. if authentication actually works.) because of said issue.

#### Additional context
The plugin author doesn't seem to be even remotely willing to add velocity support, & they seem to be inactive for a while now. Snap is my hope to finally migrate to velocity, but my current waterfall system works fine so in essence: tl;dr, this isn't really a priority.

**Comment by Phoenix616** [comment]
Only plugins using the API can be supported. This plugin seems to use internal classes not meant to be used by plugins.

I suggest finding an alternative which supports Velocity natively (pretty sure it even has events for what such a plugin needs), JPremium seems abandoned anyways.
