### ISSUE TITLE
MCStatistics doesn't work.

### ISSUE THREAD

**Issue by Khikki** [Phoenix616/Snap#24]
#### Used Version
snap 1.0-SNAPSHOT (build 23)
 
 
#### Config
 ```
{
    # configurate-hocon
    # The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
    "stats-id" : "66fe01d6-6829-477c-9ca7-a95acd8e20be",
    # configurate-hocon
    # Whether to throw exceptions when accessing methods that aren't supported
    # Setting this to false makes them return sensible values but they might not be correct
    "throw-unsupported-exception" : false
}
 ```
 
#### Environment description
MCStatistics 1.2.0 & Velocity 3.1.1
 
 
#### Full Log

```
[23:15:26] [main/INFO]: Booting up Velocity 3.1.1...
[23:15:26] [main/INFO]: Loading localizations...
[23:15:27] [main/INFO]: Connections will use epoll channels, libdeflate (Linux aarch64) compression, OpenSSL (Linux aarch64) ciphers
[23:15:27] [main/INFO]: Loading plugins...
[23:15:27] [main/INFO]: Loaded plugin snap 1.0-SNAPSHOT (build 23) by Phoenix616
[23:15:27] [main/INFO]: Loaded 1 plugins
[23:15:27] [Velocity Async Event Executor - #0/INFO]: Loaded snap.conf
[23:15:27] [Velocity Async Event Executor - #0/WARN]: Could not initialize LibraryLoader (missing dependencies?)
[23:15:27] [Velocity Async Event Executor - #0/WARN]: Error loading plugin MCStatistics
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:167) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:83) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[?:?]
	at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:120) ~[?:?]
	at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
	at de.themoep.snap.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[23:15:27] [Velocity Async Event Executor - #0/INFO]: Loaded 0 plugins!
[23:15:27] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[23:15:27] [Netty epoll Worker #0/INFO]: Listening for GS4 query on /[0:0:0:0:0:0:0:0%0]:25565
[23:15:27] [main/INFO]: Done (1.27s)!
```

#### What other programs/plugins are you running?
None.

#### What is happening?
Plugin does not start on startup.

#### What did you expect to happen?
Plugin launch.

#### Additional context
[23:15:27 WARN] [Snap]: Could not initialize LibraryLoader (missing dependencies?)

**Comment by Phoenix616** [comment]
You are trying to load a Bukkit plugin on the proxy. Snap is for BungeeCord plugins.
