### ISSUE TITLE
BungeeTabListPlus Dont work

### ISSUE THREAD

**Issue by Avalanche7CZ** [Phoenix616/Snap#27]
#### Used Version
Latest
 
 

 
#### Environment description
OS: Windows 10
Proxy: Velocity 3.1.1
Backend server versions: 1.7.10 , 1.12.2

#### Full Log
```
[23:05:00] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[23:05:00] [main/WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[23:05:00] [main/WARN]: ALL packets going through the proxy will be compressed. This will compromise throughput and increase CPU usage!
[23:05:00] [main/INFO]: Loading plugins...
[23:05:00] [main/INFO]: Loaded plugin nuvotifier 2.7.3 by Ichbinjoe
[23:05:00] [main/INFO]: Plugin has loaded!
[23:05:00] [main/INFO]: Loaded plugin omp 1.0-SNAPSHOT by zPurge
[23:05:00] [main/INFO]: Loaded plugin snap 1.0-SNAPSHOT (build 25) by Phoenix616
[23:05:00] [main/INFO]: Loaded 3 plugins
[23:05:00] [Velocity Async Event Executor - #0/INFO]: Loaded token for website: default
[23:05:00] [Velocity Async Event Executor - #0/INFO]: Using NIO transport to accept votes.
[23:05:00] [Votifier NIO boss/INFO]: Votifier enabled on socket /[0:0:0:0:0:0:0:0]:32073.
[23:05:00] [Velocity Async Event Executor - #0/INFO]: Forwarding votes over PluginMessaging channel 'nuvotifier:votes' for vote forwarding!
[23:05:00] [Velocity Async Event Executor - #0/INFO]: Loaded snap.conf
[23:05:00] [Velocity Async Event Executor - #0/WARN]: Could not initialize LibraryLoader (missing dependencies?)
[23:05:00] [Velocity Async Event Executor - #0/INFO]: Loaded plugin BungeeTabListPlus version 3.4.4 by CodeCrafter47
[23:05:01] [Velocity Async Event Executor - #0/INFO]: Starting UpdateChecker Task
[23:05:01] [Velocity Async Event Executor - #0/INFO]: Enabled plugin BungeeTabListPlus version 3.4.4 by CodeCrafter47
[23:05:01] [Velocity Async Event Executor - #0/INFO]: Loaded 1 plugins!
[23:05:01] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:XXXX
[23:05:01] [main/INFO]: Done (1,45s)!
[23:05:13] [main/INFO]: This command does not exist.
[23:05:16] [main/INFO]: This command does not exist.
[23:05:17] [main/INFO]: This command does not exist.
[23:05:27] [Netty NIO Worker #2/INFO]: [connected player] Avalanche7CZ (/XXXX) has connected
[23:05:27] [Velocity Async Event Executor - #10/ERROR]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: net/md_5/bungee/UserConnection
	at codecrafter47.bungeetablistplus.util.ReflectionUtil.getChannelWrapper(ReflectionUtil.java:37) ~[?:?]
	at codecrafter47.bungeetablistplus.managers.TabViewManager.createTabView(TabViewManager.java:126) ~[?:?]
	at codecrafter47.bungeetablistplus.managers.TabViewManager.onPlayerJoin(TabViewManager.java:71) ~[?:?]
	at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[?:?]
	at de.themoep.snap.forwarding.listener.PostLoginListener.on(PostLoginListener.java:33) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$16.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.UserConnection
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[23:05:27] [Netty NIO Worker #2/INFO]: [server connection] Avalanche7CZ -> dj has connected
[23:05:27] [Netty NIO Worker #2/INFO]: [server connection] Avalanche7CZ -> dj has disconnected
[23:05:27] [Netty NIO Worker #2/ERROR]: [connected player] Avalanche7CZ (/XXXXX): disconnected while connecting to dj: Server is still starting! Please wait before reconnecting.
[23:05:27] [Netty NIO Worker #2/INFO]: [server connection] Avalanche7CZ -> auth has connected
[23:05:27] [Velocity Async Event Executor - #15/WARN]: Error dispatching event ServerSwitchEvent(player=de.themoep.snap.forwarding.SnapPlayer@23317fe1, from=null) to listener codecrafter47.bungeetablistplus.managers.TabViewManager@7709ddbe
java.lang.AssertionError: Received ServerSwitchEvent for non-existent player Avalanche7CZ
	at codecrafter47.bungeetablistplus.managers.TabViewManager.onServerConnected(TabViewManager.java:96) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[?:?]
	at de.themoep.snap.forwarding.listener.ServerSwitchListener.on(ServerSwitchListener.java:34) ~[?:?]
	at de.themoep.snap.forwarding.listener.Lmbda$25.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[23:15:42] [Velocity Async Event Executor - #8/INFO]: Velocity 3.1.1
[23:15:42] [Velocity Async Event Executor - #8/INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[23:15:42] [Velocity Async Event Executor - #8/INFO]: velocitypowered.com - GitHub
```

#### StackTrace
```
[23:05:27 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer
in order to help resolving the problem
java.lang.NoClassDefFoundError: net/md_5/bungee/UserConnection
        at codecrafter47.bungeetablistplus.util.ReflectionUtil.getChannelWrapper(ReflectionUtil.java:37) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.createTabView(TabViewManager.java:126) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.onPlayerJoin(TabViewManager.java:71) ~[?:?]
        at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[?:?]
        at de.themoep.snap.forwarding.listener.PostLoginListener.on(PostLoginListener.java:33) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$16.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandl
er.java:47) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.1
]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.
jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.UserConnection
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 19 more
```

#### What other programs/plugins are you running?
Nuvotifier , Snap , OneMorePlus, BungeeTabListPlus 3.4.4

#### What is happening?
Tab list dont work.

#### What did you expect to happen?
Global Tab list
https://www.spigotmc.org/resources/bungeetablistplus.313/

**Comment by Phoenix616** [comment]
Please search for duplicate issues before opening new ones... (also you can't run hacky plugins/mods on Snap)

Duplicate of #14
