### ISSUE TITLE
PlasmoVoice can't read the server in velocity

### ISSUE THREAD

**Issue by KroJIak** [Phoenix616/Snap#28]
**Used Version**

snap 1.0-SNAPSHOT (build 25)

Log

[15:34:17 INFO] [snap]: Loaded snap.conf
[15:34:17 WARN] [Snap]: Could not initialize LibraryLoader (missing dependencies?)
[15:34:17 WARN] [Snap]: Error loading plugin PlasmoVoice
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:167) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:83) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:120) ~[?:?]
        at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
        at de.themoep.snap.Lmbda$11.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.1-98.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.1-98.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.1-98.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 19 more
[15:34:17 INFO] [snap]: Loaded 0 plugins!

Used the plugin Plasmovoice 1.0.8 - https://www.spigotmc.org/resources/plasmo-voice-server.91064/

The plugin does not start when the server starts, also in the snap.conf file it says "The stats/metrics ID of this proxy, ideally the same as in the velocity.toml", but there is no such item in velocity.toml. What should I do?

**Comment by Phoenix616** [comment]
You are trying to run a Bukkit plugin on the proxy, that wont work. Snap is for Bungee plugins.
