### ISSUE TITLE
ProxyPingEvent

### ISSUE THREAD

**Issue by karamzyatina** [Phoenix616/Snap#29]
[13:45:52 WARN] [Snap]: Error dispatching event ProxyPingEvent(connection=de.themoep.snap.forwarding.listener.ForwardingListener$1@6785e437, response=ServerPing(version=ServerPing.Protocol(name=Patina 1.18.1, protocol=757), players=ServerPing.Players(max=88, online=1, sample=[]), description=, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener ru.seltix.elements.events.EventListener@16b29196
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at ru.seltix.elements.events.EventListener.onPing(EventListener.java:60) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
        at de.themoep.snap.forwarding.listener.ProxyPingListener.on(ProxyPingListener.java:34) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$24.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Proxy.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Proxy.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Proxy.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
        
        
        pastebin: https://pastebin.com/3kBVC0RG

**Comment by Phoenix616** [comment]
This exception is not in Snap but occurs in a plugin's code (`at ru.seltix.elements.events.EventListener.onPing(EventListener.java:60) ~[?:?]`) because they don't properly check the list length, please contact its author so they can look at it. If they believe that this works on Bungee without issue and only appears on Snap then they should provide information such as the source code they are using and ideally some info about what state causes this error.

**Comment by karamzyatina** [comment]
The developer abandoned the plugin a long time ago, but I have the source code, slightly modified by me. I didn't change the whole plugin, just the messages
[Core.jar.zip](https://github.com/Phoenix616/Snap/files/7976294/Core.jar.zip)
. Here is the code:

**Comment by Phoenix616** [comment]
Well I took a look at your code and it has nothing to do with the Bungee API usage of it but it's some kind of bug in the plugin code itself.
