### ISSUE TITLE
Bug(maybe im stupid)

### ISSUE THREAD

**Issue by Max-109** [Phoenix616/Snap#31]
#### Config

 ```yaml
 [Put the config here]
 ```
 
#### Full Log

```

[13:43:27 ERROR]: java.sql.SQLException: No suitable driver found for jdbc:mysql                                                                                  ://Myip/ bungeecordapi
[13:43:27 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverM                                                                                  anager.java:706)
[13:43:27 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverM                                                                                  anager.java:229)
[13:43:27 ERROR]:       at kz.hengab.API.onEnable(API.java:50)
[13:43:27 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugin                                                                                  s(PluginManager.java:315)
[13:43:27 ERROR]:       at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBun                                                                                  geeAdapter.java:121)
[13:43:27 ERROR]:       at de.themoep.snap.Snap.onProxyInitialization(Snap.java:                                                                                  63)
[13:43:27 ERROR]:       at de.themoep.snap.Lmbda$2.execute(Unknown Source)
[13:43:27 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandle                                                                                  r$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[13:43:27 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.                                                                                  fire(VelocityEventManager.java:598)
[13:43:27 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.                                                                                  lambda$fire$5(VelocityEventManager.java:479)
[13:43:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.run                                                                                  Worker(ThreadPoolExecutor.java:1136)
[13:43:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Wor                                                                                  ker.run(ThreadPoolExecutor.java:635)
[13:43:27 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

```

#### What other programs/plugins are you running?
Only bungeecordapi from spigot https://www.spigotmc.org/resources/bungeecordapi.98926/

#### What is happening?
On server start im getting this error

#### What did you expect to happen?

Just getting an error while start upping
#### Additional context

https://user-images.githubusercontent.com/82242062/152999583-c1efe2b9-c384-4870-b6cf-bdf4b890c695.mp4

**Comment by Phoenix616** [comment]
Please provide the information requested in the issue template.

**Comment by rakzoser** [comment]
Done
