### ISSUE TITLE
Problem whilte /hub command

### ISSUE THREAD

**Issue by xAspired** [Phoenix616/Snap#32]
#### Used Version
Velocity 3.0.0, Snap Latest
 
 
#### Config

 ```yaml
{
    # configurate-hocon
    # The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
    "stats-id" : "85e2e3b2-79c8-40fc-ab13-2bd9990c56b4",
    # configurate-hocon
    # Whether to throw exceptions when accessing methods that aren't supported
    # Setting this to false makes them return sensible values but they might not be correct
    "throw-unsupported-exception" : true
}

 ```
 
#### Full Log
```
[22:54:05 INFO]: Exception occurred while running command for Fr0styy_
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command hub for [connected player] Fr0styy_ (/93.47.60.157:3223)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command hub for [connected player] Fr0styy_ (/93.47.60.157:3223)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[server.jar:3.1.1]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[server.jar:3.1.1]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/BungeeCord
        at com.fren_gor.hubcommand.Hub.execute(Hub.java:54) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:132) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:128) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.1.1]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.1.1]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[server.jar:3.1.1]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[server.jar:3.1.1]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.BungeeCord
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.fren_gor.hubcommand.Hub.execute(Hub.java:54) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:132) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:128) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.1.1]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.1.1]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[server.jar:3.1.1]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[server.jar:3.1.1]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

#### What other programs/plugins are you running?
LuckPerms
ServerUtils
TAB
ViaVersion
ViaRewind
ViaBackwards

#### What is happening?
I cannot use /hub command in other server.

#### What did you expect to happen?
I expect it sends me to the hub server

#### Additional context
In the hub server, I use the latest version of Java, while in factions I use Java 1.8

**Comment by Phoenix616** [comment]
The plugin that provides `com.fren_gor.hubcommand.Hub` uses the internal class `net.md_5.bungee/BungeeCord` instead of the plugin API. It's not possible to support such hacky plugins, only plugins using the plugin API are supported.
