### ISSUE TITLE
InventorySaver not working

### ISSUE THREAD

**Issue by DJelly4K** [Phoenix616/Snap#34]
#### Used Version
Loaded plugin snap 1.0-SNAPSHOT (build 25) by Phoenix616
 
 
#### Config
 ```yaml
{
    # configurate-hocon
    # The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
    "stats-id" : "483810e7-6879-4075-bb4a-dd619ae85094",
    # configurate-hocon
    # Whether to throw exceptions when accessing methods that aren't supported
    # Setting this to false makes them return sensible values but they might not be correct
    "throw-unsupported-exception" : true
}

 ```
 
#### Environment description
Windows server 2022 & [Mirai](https://github.com/etil2jz/Mirai) (a [Pufferfish](https://github.com/pufferfish-gg/Pufferfish) fork) down stream server
 
 
#### Full Log
```
[22:54:19 WARN] [Snap]: Error loading plugin InventorySaver
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:167) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:83) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:120) ~[?:?]
        at de.themoep.snap.Snap.onProxyInitialization(Snap.java:63) ~[?:?]
        at de.themoep.snap.Lmbda$26.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.2-SNAPSHOT-128.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.2-SNAPSHOT-128.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.2-SNAPSHOT-128.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 19 more
```

#### What other programs/plugins are you running?
CMIBungee, FakeProtocol

#### What is happening?
InventorySaver can't load normally

#### What did you expect to happen?
InventorySaver load normally

#### Additional context
My English is not very good and use machine translation

**Comment by Phoenix616** [comment]
You are running a Bukkit plugin on the Proxy. Don't.

**Comment by DJelly4K** [comment]
> You are running a Bukkit plugin on the Proxy. Don't.

sorry, im really stupid
