### ISSUE TITLE
FastLoginBungee incompatible

### ISSUE THREAD

**Issue by x9nico** [Phoenix616/Snap#4]
#### Used Version

 Latest build (#9)
 
#### Config

 ```yaml
 [Put the config here]
 ```
I changed nothing about config file. it's default.
 
#### Environment description

 OS: Ubuntu 20.04.2 LTS (Kernel 5.4 LTS)
Java: 11 LTS
Proxy: Velocity

 
#### Full Log

```
[Your log here]
```
There is errors:

[22:55:15 WARN] [Snap]: Exception encountered when loading plugin: FastLogin
java.lang.NoClassDefFoundError: net/md_5/bungee/connection/InitialHandler
        at com.github.games647.fastlogin.bungee.listener.ConnectListener.<clinit>(ConnectListener.java:56) ~[?:?]
        at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:60) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121) ~[?:?]
        at de.themoep.snap.Snap.onProxyInitialization(Snap.java:59) ~[?:?]
        at net.kyori.event.asm.generated.9fa8fed8c8.Snap-onProxyInitialization-ProxyInitializeEvent-11.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.4]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.4]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[velocity.jar:1.1.4]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[velocity.jar:1.1.4]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.InitialHandler
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:85) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:67) ~[?:?]
        at java.lang.ClassLoa

**Comment by Phoenix616** [comment]
The plugin seems to use internal classes and not the API so this will most likely not supportable (`net/md_5/bungee/connection/InitialHandler` is not part of the API)

**Comment by 7wOv6ySCjo** [comment]
:(

**Comment by Phoenix616** [comment]
@7wOv6ySCjo that has literally nothing to do with the error here, but Snap now supports the mentioned stats id. ;)

**Comment by 7wOv6ySCjo** [comment]
> @7wOv6ySCjo that has literally nothing to do with the error here, but Snap now supports the mentioned stats id. ;)
Nice work !!! thanks. +1 for you.
