### ISSUE TITLE
Error using zmusic plugin

### ISSUE THREAD

**Issue by HYDeath** [Phoenix616/Snap#43]
### What is happening?

After playing the music, if the log prompts an error, it cannot be played.

### What did you expect to happen?

Search and play music after normal input.

### Version

Snap 1.2-pre 1 (build 35)

### Config

```YAML
[Put the config here]
# Whether to register all forwarding listeners even though no plugin needs it
# This is required if a plugin tries to dynamically register events after its onEnable method was called
register-all-listeners=false
# The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
stats-id="83bf970b-858b-4a5e-98b1-00ed95b8c276"
# Whether to throw exceptions when accessing methods that aren't supported
# Setting this to false makes them return sensible values but they might not be correct
throw-unsupported-exception=true
```

### Server/system Version

velocity-3.3.0-SNAPSHOT-404/Windows 2022

### Log

```shell
[Put your log here]

[19:29:14 ERROR]: java.lang.UnsupportedOperationException: Unsafe is not supported by Snap!
[19:29:14 ERROR]:       at de.themoep.snap.Snap.unsupported(Snap.java:136)
[19:29:14 ERROR]:       at de.themoep.snap.forwarding.SnapPlayer.unsafe(SnapPlayer.java:497)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.lambda$setVisible$5(BossBarBC.java:173)
[19:29:14 ERROR]:       at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.setVisible(BossBarBC.java:173)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.showTitle(BossBarBC.java:41)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.music.LyricSender.initBossBar(LyricSender.java:80)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.music.LyricSender.init(LyricSender.java:54)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.music.PlayMusic.play(PlayMusic.java:161)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.music.PlayMusic.play(PlayMusic.java:103)
[19:29:14 ERROR]:       at me.zhenxin.zmusic.command.Cmd.lambda$cmd$1(Cmd.java:107)
[19:29:14 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
[19:29:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:29:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:29:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[19:29:23 ERROR]: java.lang.UnsupportedOperationException: Unsafe is not supported by Snap!
[19:29:23 ERROR]:       at de.themoep.snap.Snap.unsupported(Snap.java:136)
[19:29:23 ERROR]:       at de.themoep.snap.forwarding.SnapPlayer.unsafe(SnapPlayer.java:497)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.lambda$setVisible$5(BossBarBC.java:173)
[19:29:23 ERROR]:       at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.setVisible(BossBarBC.java:173)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.api.bossbar.BossBarBC.showTitle(BossBarBC.java:41)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.music.LyricSender.initBossBar(LyricSender.java:80)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.music.LyricSender.init(LyricSender.java:54)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.music.PlayMusic.play(PlayMusic.java:161)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.music.PlayMusic.play(PlayMusic.java:103)
[19:29:23 ERROR]:       at me.zhenxin.zmusic.command.Cmd.lambda$cmd$1(Cmd.java:107)
[19:29:23 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
[19:29:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:29:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:29:23 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
```
```


### What other programs/plugins are you running?

No other plugins

### Additional context

_No response_

**Comment by Phoenix616** [comment]
The plugin uses `getUnsafe` which can't be supported.

You can try setting `throw-unsupported-exception` and see if it (mostly) works anyways, otherwise you will hale to contact the dev of the plugin to get them to be compatible or provide a Velocity-native version.
