### ISSUE TITLE
unknown errors

### ISSUE THREAD

**Issue by TymekSL** [Phoenix616/Snap#45]
### What is happening?

During the hack controol from cleanscreenshare plugin i have errors from SNAP 

### What did you expect to happen?

1. /ss player
2. player left and should be banned automatically - he didn't 
3. errors

### Version

add versions numbers

### Config

```YAML
# Whether to register all forwarding listeners even though no plugin needs it
# This is required if a plugin tries to dynamically register events after its onEnable method was called
register-all-listeners=true
# The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
stats-id=adce4f79-5c09-4b7b-92e9-2424a3bdb113
# Whether to throw exceptions when accessing methods that aren't supported
# Setting this to false makes them return sensible values but they might not be correct
throw-unsupported-exception=false
Server/system Version
```

### Server/system Version

....[23:44:00 INFO]: Velocity 3.3.0-SNAPSHOT (git-09f687e5-b413)

### Log

```shell
[Put your log here]
```

### What other programs/plugins are you running?

https://prnt.sc/AsC9FJHJCiLO
https://prnt.sc/enn-g-ySVaFi

### Additional context

[02:01:58 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@39f43ba5, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@28bce27
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$97.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-09f687e5-b413)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-09f687e5-b413)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-09f687e5-b413)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Phoenix616** [comment]
Your issue is missing the exact version and build number of Snap that you
are using, please provide it.

**Comment by TymekSL** [comment]
you didnt add build numbers to the jar so i dont know which i using lmao add 
snap-1.1.jar

**Comment by TymekSL** [comment]
Snap 1.2-pre 1 (build 35) [Latest](https://github.com/Phoenix616/Snap/releases/latest)

**Comment by Phoenix616** [comment]
Please test if the latest dev build 36 changes anything.
