### ISSUE TITLE
lobby 

### ISSUE THREAD

**Issue by TymekSL** [Phoenix616/Snap#47]
### What is happening?

/lobby command make eerrors

### What did you expect to happen?

fix it 

### Version

Snap 1.2-pre 1 (build 35) Latest

### Config

```YAML
[Put the config here]
```

### Server/system Version

velocity-3.3.0-SNAPSHOT-436.jar

### Log

```shell
[13:43:06 INFO]: Exception occurred while running command for BloodyMonkey383
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command  lobbyfor [connected player] BloodyMonkey383 (/79.185.228.195:39068)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command  lobbyfor [connected player] BloodyMonkey383 (/79.185.228.195:39068)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:258) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$3(VelocityCommandManager.java:292) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.UnsupportedOperationException: Not implemented (yet)!
        at de.themoep.snap.Snap.unsupported(Snap.java:136) ~[?:?]
        at de.themoep.snap.forwarding.SnapServerInfo.canAccess(SnapServerInfo.java:93) ~[?:?]
        at it.fulminazzo.fastplaybungee.Utils.ServerUtils.lambda$getServers$1(ServerUtils.java:37) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at it.fulminazzo.fastplaybungee.Utils.ServerUtils.getServers(ServerUtils.java:39) ~[?:?]
        at it.fulminazzo.fastplaybungee.Utils.ServerUtils.connect(ServerUtils.java:20) ~[?:?]
        at it.fulminazzo.fastplaybungee.Commands.ConnectCommand.execute(ConnectCommand.java:19) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:157) ~[?:?]
        at de.themoep.snap.SnapBungeeAdapter$1.execute(SnapBungeeAdapter.java:153) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:82) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:236) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$3(VelocityCommandManager.java:292) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

### What other programs/plugins are you running?

https://prnt.sc/AsC9FJHJCiLO
https://prnt.sc/enn-g-ySVaFi

**Comment by Phoenix616** [comment]
Please read the [not-supported features list](https://github.com/Phoenix616/Snap#not-supported) in the readme Velocity has no concept of per-server permissions. If you don't care then you can of course toggle `throw-unsupported-exception` in the config (which you again did not provide...) but then plugins might just randomly break.

**Comment by TymekSL** [comment]
> Please read the [not-supported features list](https://github.com/Phoenix616/Snap#not-supported) in the readme Velocity has no concept of per-server permissions. If you don't care then you can of course toggle `throw-unsupported-exception` in the config (which you again did not provide...) but then plugins might just randomly break.

what velocity per-server permissions have problem with the lobby command which should going from networkmanager on velocity hm?

**Comment by Phoenix616** [comment]
> what velocity per-server permissions have problem with the lobby command which should going from networkmanager on velocity hm?

Sorry, I don't understand what you are asking.

**Comment by TymekSL** [comment]
> > what velocity per-server permissions have problem with the lobby command which should going from networkmanager on velocity hm?
> 
> Sorry, I don't understand what you are asking.

why velocity commands make problematic in your stupid plugin?

**Comment by Phoenix616** [comment]
Sorry, but I will not help people that use insults in relation to my work that I provide for **free**!
