### ISSUE TITLE
snap errors

### ISSUE THREAD

**Issue by TymekSL** [Phoenix616/Snap#48]
### What is happening?

I cant join to the serrver

### What did you expect to happen?

Problems

### Version

Snap 1.2-pre 1 (build 35) Latest

### Config

```YAML
# Whether to register all forwarding listeners even though no plugin needs it
# This is required if a plugin tries to dynamically register events after its onEnable method was called
register-all-listeners=true
# The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
stats-id=adce4f79-5c09-4b7b-92e9-2424a3bdb113
# Whether to throw exceptions when accessing methods that aren't supported
# Setting this to false makes them return sensible values but they might not be correct
throw-unsupported-exception=false
```

### Server/system Version

velocity-3.3.0-SNAPSHOT-436.jar

### Log

```shell
[02:51:37 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@33026dd9, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@115e4cc8
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$116.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:543) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:532) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer$ConnectionRequestBuilderImpl.lambda$internalConnect$3(ConnectedPlayer.java:1373) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### What other programs/plugins are you running?

https://prnt.sc/AsC9FJHJCiLO
https://prnt.sc/enn-g-ySVaFi

### Additional context

Please explain why there is problem with join

**Comment by Phoenix616** [comment]
I would really appreciate it if you wouldn't open the same issue again and again... especially as #45 was already fixed. Update to the latest build!
