### ISSUE TITLE
Problem with sending

### ISSUE THREAD

**Issue by TymekSL** [Phoenix616/Snap#50]
### What is happening?

[00:39:14 INFO] [simpleproxychat]: [ProxyNotifier] [+] Gracz DeadMan712 | 12:39 AM (auth)
[00:39:19 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@514a24fe, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@48bca6
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$120.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:543) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:532) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer$ConnectionRequestBuilderImpl.lambda$internalConnect$3(ConnectedPlayer.java:1373) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]

### What did you expect to happen?

Problem has been happened when I trying move player who has not login yet, so he is on the auth server and need to login, I using command send all hardsmp then got errors 

### Version

Snap 1.2-pre 1 (build 35) Latest

### Config

```YAML
Nothing has been changed
```

### Server/system Version

velocity-3.3.0-SNAPSHOT-436.jar

### Log

```shell
You ignored all my logs so won't waste my time xD
```

### What other programs/plugins are you running?

.

**Comment by Phoenix616** [comment]
You are running an outdated build. This should already be fixed by 91c7cb96f22c0ca1b31647ab3956488089bdccc8. Please test it.
