### ISSUE TITLE
Litebans Error

### ISSUE THREAD

**Issue by NovaPixell** [Phoenix616/Snap#8]
When joining the server, in console there is this error:

[14:29:05 ERROR]: Exception in thread "LiteBans Dedicated Pool Thread #0" java.lang.UnsupportedOperationException: Not implemented (yet)!
[14:29:05 ERROR]: at de.themoep.snap.Snap.unsupported(Snap.java:123)
[14:29:05 ERROR]: at de.themoep.snap.forwarding.SnapProxyServer.getReconnectHandler(SnapProxyServer.java:233)
[14:29:05 ERROR]: at litebans.aa.a(aa.java:57)
[14:29:05 ERROR]: at litebans.c9.a(c9.java:37)
[14:29:05 ERROR]: at litebans.c9.a(c9.java:3)
[14:29:05 ERROR]: at litebans.ad.a(ad.java:567)
[14:29:05 ERROR]: at litebans.hK.a(hK.java:7)
[14:29:05 ERROR]: at litebans.hK.a(hK.java:31)
[14:29:05 ERROR]: at litebans.gJ.run(gJ.java:5)
[14:29:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:29:05 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:29:05 ERROR]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Phoenix616** [comment]
This is to be expected, Velocity doesn't have a concept of a reconnect handler. If you want it to not throw the error then adjust the Snap config.

**Comment by kubo6472** [comment]
@NovaPixell 

```
# Whether to throw exceptions when accessing methods that aren't supported
# Setting this to false makes them return sensible values but they might not be correct
throw-unsupported-exception = false
```

**Comment by refractored** [comment]
Litebans supports velocity?
