### ISSUE TITLE
UltimateFriends Not Supported

### ISSUE THREAD

**Issue by mertkaan33** [Phoenix616/Snap#9]
[16:59:08 ERROR]: java.lang.IllegalArgumentException: Unknown storage
[16:59:08 ERROR]:       at com.gmail.holubvojtech.ultimatefriends.Config.loadStorage(Config.java:449)
[16:59:08 ERROR]:       at com.gmail.holubvojtech.ultimatefriends.Config.<init>(Config.java:75)
[16:59:08 ERROR]:       at com.gmail.holubvojtech.ultimatefriends.UltimateFriends.onEnable(UltimateFriends.java:85)
[16:59:08 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
[16:59:08 ERROR]:       at de.themoep.snap.SnapBungeeAdapter.loadPlugins(SnapBungeeAdapter.java:121)
[16:59:08 ERROR]:       at de.themoep.snap.Snap.onProxyInitialization(Snap.java:59)
[16:59:08 ERROR]:       at net.kyori.event.asm.generated.960525be95.Snap-onProxyInitialization-ProxyInitializeEvent-1.invoke(Unknown Source)
[16:59:08 ERROR]:       at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148)
[16:59:08 ERROR]:       at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107)
[16:59:08 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154)
[16:59:08 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136)
[16:59:08 ERROR]:       at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[16:59:08 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:59:08 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:59:08 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[16:59:08 ERROR] [UltimateFriends]: Cannot load config: Unknown storage
[16:59:08 ERROR] [UltimateFriends]: Exiting...

**Comment by Phoenix616** [comment]
The only plugin by that nae that I can find is a private, paid one so if that is indeed it then you are going to have to contact its author form them to provide some information what went wrong there.

Also it would be helpful if you provided the rest of the requested information from the issue template that you omitted...

**Comment by kubo6472** [comment]
@xcrexus 
1. Don't crack paid plugins
2. The guy has a public discord server
3. USE THE TEMPLATE

**Comment by kubo6472** [comment]
@Phoenix616 it was a config error, as says the plugin author, who was in contact with @xcrexus 
![image](https://user-images.githubusercontent.com/26146502/125126314-2fe6cc80-e0fb-11eb-80b6-34bcfb65bb0b.png)
-Plugin Author
So this can be closed as well.
